from typing import Any

revision: str
down_revision: str
branch_labels: Any
depends_on: Any
TABLE_NAME: str
INDEX_NAME: Any

def mssql_timestamp(): ...
def mysql_timestamp(): ...
def sa_timestamp(): ...
def upgrade() -> None: ...
def downgrade() -> None: ...
