from typing import Any

revision: str
down_revision: str
branch_labels: Any
depends_on: Any

def upgrade() -> None: ...
def downgrade() -> None: ...
def get_table_constraints(conn, table_name): ...
def reorder_columns(columns): ...
def drop_constraint(operator, constraint_dict) -> None: ...
def create_constraint(operator, constraint_dict) -> None: ...
def modify_execution_date_with_constraint(conn, batch_operator, table_name, type_, nullable) -> None: ...
