from ...models import BaseResource
from ..key import Key as Key
from .feature import AccountFeature as AccountFeature

class Account(BaseResource):
    def keys(self, **kwargs): ...
    def add_key(self, key): ...
    def remove_key(self, key_or_fingerprint): ...
    def disable_feature(self, id_or_name): ...
    def enable_feature(self, id_or_name): ...
    def update_feature(self, id_or_name, enabled): ...
    def change_password(self, current_password, new_password): ...
