from .. import BaseResource as BaseResource
from typing import Any

class AccountFeature(BaseResource):
    app: Any
    def __init__(self) -> None: ...
    def update(self, enabled): ...
    def enable(self): ...
    def disable(self): ...
