from airflow.kubernetes.k8s_model import K8SModel as K8SModel
from typing import Any

class Resources(K8SModel):
    request_memory: Any
    request_cpu: Any
    request_ephemeral_storage: Any
    limit_memory: Any
    limit_cpu: Any
    limit_gpu: Any
    limit_ephemeral_storage: Any
    def __init__(self, request_memory: Any | None = ..., request_cpu: Any | None = ..., request_ephemeral_storage: Any | None = ..., limit_memory: Any | None = ..., limit_cpu: Any | None = ..., limit_gpu: Any | None = ..., limit_ephemeral_storage: Any | None = ...) -> None: ...
    def is_empty_resource_request(self): ...
    def has_limits(self): ...
    def has_requests(self): ...
    def to_k8s_client_obj(self): ...
    def attach_to_pod(self, pod): ...

class Port(K8SModel):
    name: Any
    container_port: Any
    def __init__(self, name: Any | None = ..., container_port: Any | None = ...) -> None: ...
    def to_k8s_client_obj(self): ...
    def attach_to_pod(self, pod): ...
