from airflow.kubernetes.k8s_model import K8SModel as K8SModel
from typing import Any

class PodRuntimeInfoEnv(K8SModel):
    name: Any
    field_path: Any
    def __init__(self, name, field_path) -> None: ...
    def to_k8s_client_obj(self): ...
    def attach_to_pod(self, pod): ...
