from kubernetes.client import Configuration
from kubernetes.config.kube_config import KubeConfigLoader
from typing import Any

class RefreshKubeConfigLoader(KubeConfigLoader):
    api_key_expire_ts: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def refresh_api_key(self, client_configuration) -> None: ...
    def load_and_set(self, client_configuration) -> None: ...

class RefreshConfiguration(Configuration):
    refresh_api_key: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def get_api_key_with_prefix(self, identifier): ...

def load_kube_config(client_configuration, config_file: Any | None = ..., context: Any | None = ...) -> None: ...
