from airflow.exceptions import AirflowConfigException as AirflowConfigException
from airflow.kubernetes.k8s_model import K8SModel as K8SModel
from typing import Any

class Secret(K8SModel):
    deploy_type: Any
    deploy_target: Any
    secret: Any
    key: Any
    def __init__(self, deploy_type, deploy_target, secret, key: Any | None = ...) -> None: ...
    def to_env_secret(self): ...
    def to_env_from_secret(self): ...
    def to_volume_secret(self): ...
    def attach_to_pod(self, pod): ...
    def __eq__(self, other): ...
