from airflow.hooks.dbapi_hook import DbApiHook as DbApiHook
from typing import Any

class PostgresHook(DbApiHook):
    conn_name_attr: str
    default_conn_name: str
    supports_autocommit: bool
    schema: Any
    def __init__(self, *args, **kwargs) -> None: ...
    conn: Any
    def get_conn(self): ...
    def copy_expert(self, sql, filename, open=...) -> None: ...
    def bulk_load(self, table, tmp_file) -> None: ...
    def bulk_dump(self, table, tmp_file) -> None: ...
    def get_iam_token(self, conn): ...
