from airflow.hooks.base_hook import BaseHook as BaseHook
from typing import Any

class SambaHook(BaseHook):
    conn: Any
    def __init__(self, samba_conn_id) -> None: ...
    def get_conn(self): ...
    def push_from_local(self, destination_filepath, local_filepath) -> None: ...
