from typing import Any

def max_partition(table, schema: str = ..., field: Any | None = ..., filter_map: Any | None = ..., metastore_conn_id: str = ...): ...
def closest_ds_partition(table, ds, before: bool = ..., schema: str = ..., metastore_conn_id: str = ...): ...
