from typing import Any

class Client:
    def __init__(self, api_base_url, auth) -> None: ...
    def trigger_dag(self, dag_id, run_id: Any | None = ..., conf: Any | None = ..., execution_date: Any | None = ...) -> None: ...
    def delete_dag(self, dag_id) -> None: ...
    def get_pool(self, name) -> None: ...
    def get_pools(self) -> None: ...
    def create_pool(self, name, slots, description) -> None: ...
    def delete_pool(self, name) -> None: ...
