from airflow.configuration import conf as conf
from airflow.executors.base_executor import BaseExecutor as BaseExecutor
from typing import Any

class DaskExecutor(BaseExecutor):
    cluster_address: Any
    tls_ca: Any
    tls_key: Any
    tls_cert: Any
    def __init__(self, cluster_address: Any | None = ...) -> None: ...
    client: Any
    futures: Any
    def start(self) -> None: ...
    def execute_async(self, key, command, queue: Any | None = ..., executor_config: Any | None = ...): ...
    def sync(self) -> None: ...
    def end(self) -> None: ...
    def terminate(self) -> None: ...
