from airflow.sensors.hdfs_sensor import HdfsSensor as HdfsSensor
from typing import Any

class HdfsSensorRegex(HdfsSensor):
    regex: Any
    def __init__(self, regex, *args, **kwargs) -> None: ...
    def poke(self, context): ...

class HdfsSensorFolder(HdfsSensor):
    be_empty: Any
    def __init__(self, be_empty: bool = ..., *args, **kwargs) -> None: ...
    def poke(self, context): ...
