from airflow.utils.db import create_session as create_session

def register_pre_exec_callback(action_logger) -> None: ...
def register_post_exec_callback(action_logger) -> None: ...
def on_pre_execution(**kwargs) -> None: ...
def on_post_execution(**kwargs) -> None: ...
def default_action_log(log, **_) -> None: ...
