from airflow import settings as settings
from airflow.configuration import conf as conf
from typing import Any

log: Any

def create_session() -> None: ...
def provide_session(func): ...
def merge_conn(conn, session: Any | None = ...) -> None: ...
def add_default_pool_if_not_exists(session: Any | None = ...) -> None: ...
def create_default_connections(session: Any | None = ...) -> None: ...
def initdb(rbac: bool = ...) -> None: ...
def upgradedb() -> None: ...
def resetdb(rbac) -> None: ...
def checkdb(session: Any | None = ...) -> None: ...
