from airflow.configuration import conf as conf
from airflow.exceptions import AirflowConfigException as AirflowConfigException
from typing import Any, Iterable, List, Union

log: Any

def send_email(to, subject, html_content, files: Any | None = ..., dryrun: bool = ..., cc: Any | None = ..., bcc: Any | None = ..., mime_subtype: str = ..., mime_charset: str = ..., **kwargs): ...
def send_email_smtp(to, subject, html_content, files: Any | None = ..., dryrun: bool = ..., cc: Any | None = ..., bcc: Any | None = ..., mime_subtype: str = ..., mime_charset: str = ..., **kwargs) -> None: ...
def send_MIME_email(e_from, e_to, mime_msg, dryrun: bool = ...) -> None: ...
def get_email_address_list(addresses: Union[str, Iterable[str]]) -> List[str]: ...
