from airflow.exceptions import AirflowTaskTimeout as AirflowTaskTimeout
from airflow.utils.log.logging_mixin import LoggingMixin as LoggingMixin
from typing import Any

class timeout(LoggingMixin):
    seconds: Any
    error_message: Any
    def __init__(self, seconds: int = ..., error_message: str = ...) -> None: ...
    def handle_timeout(self, signum, frame) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, type, value, traceback) -> None: ...
