from airflow.settings import TIMEZONE as TIMEZONE
from typing import Any

utc: Any

def is_localized(value): ...
def is_naive(value): ...
def utcnow(): ...
def utc_epoch(): ...
def convert_to_utc(value): ...
def make_aware(value, timezone: Any | None = ...): ...
def make_naive(value, timezone: Any | None = ...): ...
def datetime(*args, **kwargs): ...
def parse(string, timezone: Any | None = ...): ...
