from airflow.executors.base_executor import BaseExecutor as BaseExecutor
from airflow.utils.state import State as State
from typing import Any

class SequentialExecutor(BaseExecutor):
    commands_to_run: Any
    def __init__(self) -> None: ...
    def execute_async(self, key, command, queue: Any | None = ..., executor_config: Any | None = ...) -> None: ...
    def sync(self) -> None: ...
    def end(self) -> None: ...
