from airflow.configuration import conf as conf
from typing import Any

NEED_KRB181_WORKAROUND: Any
log: Any

def renew_from_kt(principal, keytab) -> None: ...
def perform_krb181_workaround(principal) -> None: ...
def detect_conf_var(): ...
def run(principal, keytab) -> None: ...
