from airflow.utils.net import get_hostname as get_hostname
from typing import Any

def get_components(principal): ...
def replace_hostname_pattern(components, host: Any | None = ...): ...
def get_fqdn(hostname_or_ip: Any | None = ...): ...
def principal_from_username(username, realm): ...
