from airflow import models as models, settings as settings
from airflow.utils.db import provide_session as provide_session
from flask_login import current_user as current_user, login_required as login_required, logout_user as logout_user
from typing import Any

DEFAULT_USERNAME: str
LOGIN_MANAGER: Any

class DefaultUser:
    user: Any
    def __init__(self, user) -> None: ...
    @property
    def is_active(self): ...
    @property
    def is_authenticated(self): ...
    @property
    def is_anonymous(self): ...
    def data_profiling(self): ...
    def is_superuser(self): ...

def load_user(userid, session: Any | None = ...): ...
def login(self, request, session: Any | None = ...): ...
