from airflow.api.client import api_client as api_client
from airflow.api.common.experimental import delete_dag as delete_dag, pool as pool, trigger_dag as trigger_dag
from typing import Any

class Client(api_client.Client):
    def trigger_dag(self, dag_id, run_id: Any | None = ..., conf: Any | None = ..., execution_date: Any | None = ...): ...
    def delete_dag(self, dag_id): ...
    def get_pool(self, name): ...
    def get_pools(self): ...
    def create_pool(self, name, slots, description): ...
    def delete_pool(self, name): ...
