from airflow.contrib.hooks.aws_hook import AwsHook as AwsHook
from typing import Any

class SQSHook(AwsHook):
    def get_conn(self): ...
    def create_queue(self, queue_name, attributes: Any | None = ...): ...
    def send_message(self, queue_url, message_body, delay_seconds: int = ..., message_attributes: Any | None = ...): ...
