from airflow.contrib.hooks.qubole_hook import QuboleHook as QuboleHook
from airflow.exceptions import AirflowException as AirflowException
from typing import Any

COL_DELIM: str
ROW_DELIM: str
log: Any

def isint(value): ...
def isfloat(value): ...
def isbool(value): ...
def parse_first_row(row_list): ...

class QuboleCheckHook(QuboleHook):
    results_parser_callable: Any
    context: Any
    def __init__(self, context, *args, **kwargs) -> None: ...
    @staticmethod
    def handle_failure_retry(context) -> None: ...
    def get_first(self, sql): ...
    def get_query_results(self): ...
