from airflow.contrib.hooks.aws_hook import AwsHook as AwsHook

class RedshiftHook(AwsHook):
    def get_conn(self): ...
    def cluster_status(self, cluster_identifier): ...
    def delete_cluster(self, cluster_identifier, skip_final_cluster_snapshot: bool = ..., final_cluster_snapshot_identifier: str = ...): ...
    def describe_cluster_snapshots(self, cluster_identifier): ...
    def restore_from_cluster_snapshot(self, cluster_identifier, snapshot_identifier): ...
    def create_cluster_snapshot(self, snapshot_identifier, cluster_identifier): ...
