from airflow.contrib.hooks.ssh_hook import SSHHook as SSHHook
from typing import Any

class SFTPHook(SSHHook):
    conn: Any
    private_key_pass: Any
    no_host_key_check: bool
    key_file: Any
    def __init__(self, ftp_conn_id: str = ..., *args, **kwargs) -> None: ...
    def get_conn(self): ...
    def close_conn(self) -> None: ...
    def describe_directory(self, path): ...
    def list_directory(self, path): ...
    def create_directory(self, path, mode: int = ...) -> None: ...
    def delete_directory(self, path) -> None: ...
    def retrieve_file(self, remote_full_path, local_full_path) -> None: ...
    def store_file(self, remote_full_path, local_full_path) -> None: ...
    def delete_file(self, path) -> None: ...
    def get_mod_time(self, path): ...
    def path_exists(self, path): ...
