from airflow.configuration import conf as conf
from airflow.utils.configuration import tmp_configuration_copy as tmp_configuration_copy
from airflow.utils.log.logging_mixin import LoggingMixin as LoggingMixin
from airflow.utils.net import get_hostname as get_hostname
from typing import Any

PYTHONPATH_VAR: str

class BaseTaskRunner(LoggingMixin):
    run_as_user: Any
    process: Any
    def __init__(self, local_task_job) -> None: ...
    def run_command(self, run_with: Any | None = ..., join_args: bool = ...): ...
    def start(self) -> None: ...
    def return_code(self) -> None: ...
    def terminate(self) -> None: ...
    def on_finish(self) -> None: ...
