from airflow import models as models
from airflow.configuration import AirflowConfigException as AirflowConfigException, conf as conf
from airflow.utils.db import provide_session as provide_session
from flask_login import current_user as current_user, login_required as login_required, logout_user as logout_user
from typing import Any

log: Any

def get_config_param(param): ...

class GHEUser(models.User):
    user: Any
    def __init__(self, user) -> None: ...
    @property
    def is_active(self): ...
    @property
    def is_authenticated(self): ...
    @property
    def is_anonymous(self): ...
    def get_id(self): ...
    def data_profiling(self): ...
    def is_superuser(self): ...

class AuthenticationError(Exception): ...

class GHEAuthBackend:
    ghe_host: Any
    login_manager: Any
    flask_app: Any
    ghe_oauth: Any
    api_url: Any
    def __init__(self) -> None: ...
    def ghe_api_route(self, leaf): ...
    def init_app(self, flask_app) -> None: ...
    def login(self, request): ...
    def get_ghe_user_profile_info(self, ghe_token): ...
    def ghe_team_check(self, username, ghe_token): ...
    def load_user(self, userid, session: Any | None = ...): ...
    def oauth_callback(self, session: Any | None = ...): ...

LOGIN_MANAGER: Any

def login(self, request): ...
