from airflow.exceptions import AirflowBadRequest as AirflowBadRequest, PoolNotFound as PoolNotFound
from airflow.models import Pool as Pool
from airflow.utils.db import provide_session as provide_session
from typing import Any

def get_pool(name, session: Any | None = ...): ...
def get_pools(session: Any | None = ...): ...
def create_pool(name, slots, description, session: Any | None = ...): ...
def delete_pool(name, session: Any | None = ...): ...
