from airflow.models.base import Base as Base
from airflow.ti_deps.deps.pool_slots_available_dep import STATES_TO_COUNT_AS_RUNNING as STATES_TO_COUNT_AS_RUNNING
from airflow.utils.db import provide_session as provide_session
from airflow.utils.state import State as State
from typing import Any

class Pool(Base):
    __tablename__: str
    id: Any
    pool: Any
    slots: Any
    description: Any
    DEFAULT_POOL_NAME: str
    @staticmethod
    def get_pool(pool_name, session: Any | None = ...): ...
    @staticmethod
    def get_default_pool(session: Any | None = ...): ...
    def to_json(self): ...
    def occupied_slots(self, session): ...
    def used_slots(self, session): ...
    def queued_slots(self, session): ...
    def open_slots(self, session): ...
