from typing import Any

class ConfigVars:
    def __init__(self, data, app, h: Any | None = ..., **kwargs) -> None: ...
    def __contains__(self, key): ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...
    def __delitem__(self, key) -> None: ...
    def update(self, newconf) -> None: ...
    def to_dict(self): ...
    dict: Any
    @classmethod
    def new_from_dict(cls, d, h: Any | None = ..., **kwargs): ...
