from . import BaseResource as BaseResource
from .release import Release as Release
from typing import Any

class RestartRunException(Exception): ...

class Dyno(BaseResource):
    app: Any
    def __init__(self) -> None: ...
    def kill(self): ...
    def restart(self): ...
