from . import BaseResource as BaseResource
from typing import Any

class LogSession(BaseResource):
    app: Any
    def __init__(self) -> None: ...
    def stream(self, timeout: bool = ...): ...
    def get(self, timeout: bool = ...): ...
