from airflow import models as models
from airflow.configuration import conf as conf
from airflow.utils.db import provide_session as provide_session
from flask_login import current_user as current_user, login_required as login_required, logout_user as logout_user
from typing import Any

log: Any

def get_config_param(param): ...

class GoogleUser(models.User):
    user: Any
    def __init__(self, user) -> None: ...
    @property
    def is_active(self): ...
    @property
    def is_authenticated(self): ...
    @property
    def is_anonymous(self): ...
    def get_id(self): ...
    def data_profiling(self): ...
    def is_superuser(self): ...

class AuthenticationError(Exception): ...

class GoogleAuthBackend:
    login_manager: Any
    flask_app: Any
    google_oauth: Any
    api_rev: Any
    def __init__(self) -> None: ...
    def init_app(self, flask_app) -> None: ...
    def login(self, request): ...
    def get_google_user_profile_info(self, google_token): ...
    def domain_check(self, email): ...
    def load_user(self, userid, session: Any | None = ...): ...
    def oauth_callback(self, session: Any | None = ...): ...

LOGIN_MANAGER: Any

def login(self, request): ...
