from typing import Any

class KeyedListResource:
    def __init__(self, items: Any | None = ...) -> None: ...
    def __len__(self): ...
    def __iter__(self): ...
    def __getitem__(self, key): ...
    def __contains__(self, key): ...
    def add(self, *args, **kwargs): ...
    def remove(self, key): ...
    def get(self, key): ...
    def __delitem__(self, key) -> None: ...
    def append(self, items) -> None: ...
    def change_connection(self, h): ...

class DynoListResource(KeyedListResource):
    def __init__(self, *args, **kwargs) -> None: ...
    def __getitem__(self, key): ...

class DynoTypeListResource(DynoListResource):
    def __init__(self, *args, **kwargs) -> None: ...

class SSHKeyListResource(KeyedListResource):
    def __init__(self, *args, **kwargs) -> None: ...

class FilteredListResource(KeyedListResource):
    filter_func: Any
    def __init__(self, items: Any | None = ...) -> None: ...

def filtered_key_list_resource_factory(filter_func): ...
