from airflow.models.connection import Connection
from airflow.secrets.base_secrets import BaseSecretsBackend as BaseSecretsBackend
from typing import List, Optional

def get_connections(conn_id: str) -> List[Connection]: ...
def get_variable(key: str) -> Optional[str]: ...
def get_custom_secret_backend() -> Optional[BaseSecretsBackend]: ...
