from typing import Any, Optional

class BaseSecretsBackend:
    __metaclass__: Any
    def __init__(self, **kwargs) -> None: ...
    @staticmethod
    def build_path(path_prefix: str, secret_id: str, sep: str = ...) -> str: ...
    def get_conn_uri(self, conn_id: str) -> Optional[str]: ...
    def get_connections(self, conn_id): ...
    def get_variable(self, key: str) -> Optional[str]: ...
    def get_config(self, key: str) -> Optional[str]: ...
