from . import hive as hive
from random import random as random
from typing import Any

def ds_add(ds, days): ...
def ds_format(ds, input_format, output_format): ...
def datetime_diff_for_humans(dt, since: Any | None = ...): ...
