from airflow import AirflowException as AirflowException
from airflow.configuration import conf as conf
from airflow.utils.file import mkdirs as mkdirs
from typing import Any, Dict

LOG_LEVEL: Any
FAB_LOG_LEVEL: Any
LOG_FORMAT: Any
COLORED_LOG_FORMAT: Any
COLORED_LOG: Any
COLORED_FORMATTER_CLASS: Any
BASE_LOG_FOLDER: Any
PROCESSOR_LOG_FOLDER: Any
DAG_PROCESSOR_MANAGER_LOG_LOCATION: Any
FILENAME_TEMPLATE: Any
PROCESSOR_FILENAME_TEMPLATE: Any
FORMATTER_CLASS_KEY: Any
DEFAULT_LOGGING_CONFIG: Dict[str, Any]
DEFAULT_DAG_PARSING_LOGGING_CONFIG: Any
processor_manager_handler_config: Any
directory: Any
REMOTE_LOGGING: Any
ELASTICSEARCH_HOST: Any
REMOTE_BASE_LOG_FOLDER: Any
S3_REMOTE_HANDLERS: Any
GCS_REMOTE_HANDLERS: Any
WASB_REMOTE_HANDLERS: Any
ELASTICSEARCH_LOG_ID_TEMPLATE: Any
ELASTICSEARCH_END_OF_LOG_MARK: Any
ELASTICSEARCH_WRITE_STDOUT: Any
ELASTICSEARCH_JSON_FORMAT: Any
ELASTICSEARCH_JSON_FIELDS: Any
ELASTIC_REMOTE_HANDLERS: Any
