from airflow.contrib.hooks.aws_hook import AwsHook as AwsHook
from typing import Any

class AwsLogsHook(AwsHook):
    region_name: Any
    def __init__(self, region_name: Any | None = ..., *args, **kwargs) -> None: ...
    def get_conn(self): ...
    def get_log_events(self, log_group, log_stream_name, start_time: int = ..., skip: int = ..., start_from_head: bool = ...) -> None: ...
