from airflow.hooks.base_hook import BaseHook as BaseHook
from typing import Any

class AzureContainerVolumeHook(BaseHook):
    conn_id: Any
    def __init__(self, wasb_conn_id: str = ...) -> None: ...
    def get_storagekey(self): ...
    def get_file_volume(self, mount_name, share_name, storage_account_name, read_only: bool = ...): ...
