from airflow.hooks.base_hook import BaseHook as BaseHook
from typing import Any

class AzureFileShareHook(BaseHook):
    conn_id: Any
    connection: Any
    def __init__(self, wasb_conn_id: str = ...) -> None: ...
    def get_conn(self): ...
    def check_for_directory(self, share_name, directory_name, **kwargs): ...
    def check_for_file(self, share_name, directory_name, file_name, **kwargs): ...
    def list_directories_and_files(self, share_name, directory_name: Any | None = ..., **kwargs): ...
    def create_directory(self, share_name, directory_name, **kwargs): ...
    def get_file(self, file_path, share_name, directory_name, file_name, **kwargs) -> None: ...
    def get_file_to_stream(self, stream, share_name, directory_name, file_name, **kwargs) -> None: ...
    def load_file(self, file_path, share_name, directory_name, file_name, **kwargs) -> None: ...
    def load_string(self, string_data, share_name, directory_name, file_name, **kwargs) -> None: ...
    def load_stream(self, stream, share_name, directory_name, file_name, count, **kwargs) -> None: ...
