from airflow.hooks.base_hook import BaseHook as BaseHook
from typing import Any

class AzureDataLakeHook(BaseHook):
    conn_id: Any
    connection: Any
    def __init__(self, azure_data_lake_conn_id: str = ...) -> None: ...
    account_name: Any
    def get_conn(self): ...
    def check_for_file(self, file_path): ...
    def upload_file(self, local_path, remote_path, nthreads: int = ..., overwrite: bool = ..., buffersize: int = ..., blocksize: int = ...) -> None: ...
    def download_file(self, local_path, remote_path, nthreads: int = ..., overwrite: bool = ..., buffersize: int = ..., blocksize: int = ...) -> None: ...
    def list(self, path): ...
