from airflow.hooks.base_hook import BaseHook as BaseHook
from typing import Any

def mlsd(conn, path: str = ..., facts: Any | None = ...) -> None: ...

class FTPHook(BaseHook):
    ftp_conn_id: Any
    conn: Any
    def __init__(self, ftp_conn_id: str = ...) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type, exc_val, exc_tb) -> None: ...
    def get_conn(self): ...
    def close_conn(self) -> None: ...
    def describe_directory(self, path): ...
    def list_directory(self, path, nlst: bool = ...): ...
    def create_directory(self, path) -> None: ...
    def delete_directory(self, path) -> None: ...
    def retrieve_file(self, remote_full_path, local_full_path_or_buffer, callback: Any | None = ...) -> None: ...
    def store_file(self, remote_full_path, local_full_path_or_buffer) -> None: ...
    def delete_file(self, path) -> None: ...
    def rename(self, from_name, to_name): ...
    def get_mod_time(self, path): ...
    def get_size(self, path): ...

class FTPSHook(FTPHook):
    conn: Any
    def get_conn(self): ...
