from airflow.contrib.hooks.gcp_api_base_hook import GoogleCloudBaseHook as GoogleCloudBaseHook
from typing import Any

class PubSubException(Exception): ...

class PubSubHook(GoogleCloudBaseHook):
    def __init__(self, gcp_conn_id: str = ..., delegate_to: Any | None = ...) -> None: ...
    def get_conn(self): ...
    def publish(self, project, topic, messages) -> None: ...
    def create_topic(self, project, topic, fail_if_exists: bool = ...) -> None: ...
    def delete_topic(self, project, topic, fail_if_not_exists: bool = ...) -> None: ...
    def create_subscription(self, topic_project, topic, subscription: Any | None = ..., subscription_project: Any | None = ..., ack_deadline_secs: int = ..., fail_if_exists: bool = ...): ...
    def delete_subscription(self, project, subscription, fail_if_not_exists: bool = ...) -> None: ...
    def pull(self, project, subscription, max_messages, return_immediately: bool = ...): ...
    def acknowledge(self, project, subscription, ack_ids) -> None: ...
