from airflow.contrib.hooks.gcp_api_base_hook import GoogleCloudBaseHook as GoogleCloudBaseHook
from typing import Any

class CloudVideoIntelligenceHook(GoogleCloudBaseHook):
    def __init__(self, gcp_conn_id: str = ..., delegate_to: Any | None = ...) -> None: ...
    def get_conn(self): ...
    def annotate_video(self, input_uri: Any | None = ..., input_content: Any | None = ..., features: Any | None = ..., video_context: Any | None = ..., output_uri: Any | None = ..., location: Any | None = ..., retry: Any | None = ..., timeout: Any | None = ..., metadata: Any | None = ...): ...
