from airflow import AirflowException as AirflowException
from airflow.contrib.hooks.gcp_api_base_hook import GoogleCloudBaseHook as GoogleCloudBaseHook
from typing import Any

DLP_JOB_PATH_PATTERN: str
TIME_TO_SLEEP_IN_SECONDS: int

class CloudDLPHook(GoogleCloudBaseHook):
    def __init__(self, gcp_conn_id: str = ..., delegate_to: Any | None = ...) -> None: ...
    def get_conn(self): ...
    def cancel_dlp_job(self, dlp_job_id, project_id: Any | None = ..., retry: Any | None = ..., timeout: Any | None = ..., metadata: Any | None = ...) -> None: ...
    def create_deidentify_template(self, organization_id: Any | None = ..., project_id: Any | None = ..., deidentify_template: Any | None = ..., template_id: Any | None = ..., retry: Any | None = ..., timeout: Any | None = ..., metadata: Any | None = ...): ...
    def create_dlp_job(self, project_id: Any | None = ..., inspect_job: Any | None = ..., risk_job: Any | None = ..., job_id: Any | None = ..., retry: Any | None = ..., timeout: Any | None = ..., metadata: Any | None = ..., wait_until_finished: bool = ...): ...
    def create_inspect_template(self, organization_id: Any | None = ..., project_id: Any | None = ..., inspect_template: Any | None = ..., template_id: Any | None = ..., retry: Any | None = ..., timeout: Any | None = ..., metadata: Any | None = ...): ...
    def create_job_trigger(self, project_id: Any | None = ..., job_trigger: Any | None = ..., trigger_id: Any | None = ..., retry: Any | None = ..., timeout: Any | None = ..., metadata: Any | None = ...): ...
    def create_stored_info_type(self, organization_id: Any | None = ..., project_id: Any | None = ..., config: Any | None = ..., stored_info_type_id: Any | None = ..., retry: Any | None = ..., timeout: Any | None = ..., metadata: Any | None = ...): ...
    def deidentify_content(self, project_id: Any | None = ..., deidentify_config: Any | None = ..., inspect_config: Any | None = ..., item: Any | None = ..., inspect_template_name: Any | None = ..., deidentify_template_name: Any | None = ..., retry: Any | None = ..., timeout: Any | None = ..., metadata: Any | None = ...): ...
    def delete_deidentify_template(self, template_id, organization_id: Any | None = ..., project_id: Any | None = ..., retry: Any | None = ..., timeout: Any | None = ..., metadata: Any | None = ...) -> None: ...
    def delete_dlp_job(self, dlp_job_id, project_id: Any | None = ..., retry: Any | None = ..., timeout: Any | None = ..., metadata: Any | None = ...) -> None: ...
    def delete_inspect_template(self, template_id, organization_id: Any | None = ..., project_id: Any | None = ..., retry: Any | None = ..., timeout: Any | None = ..., metadata: Any | None = ...) -> None: ...
    def delete_job_trigger(self, job_trigger_id, project_id: Any | None = ..., retry: Any | None = ..., timeout: Any | None = ..., metadata: Any | None = ...) -> None: ...
    def delete_stored_info_type(self, stored_info_type_id, organization_id: Any | None = ..., project_id: Any | None = ..., retry: Any | None = ..., timeout: Any | None = ..., metadata: Any | None = ...) -> None: ...
    def get_deidentify_template(self, template_id, organization_id: Any | None = ..., project_id: Any | None = ..., retry: Any | None = ..., timeout: Any | None = ..., metadata: Any | None = ...): ...
    def get_dlp_job(self, dlp_job_id, project_id: Any | None = ..., retry: Any | None = ..., timeout: Any | None = ..., metadata: Any | None = ...): ...
    def get_inspect_template(self, template_id, organization_id: Any | None = ..., project_id: Any | None = ..., retry: Any | None = ..., timeout: Any | None = ..., metadata: Any | None = ...): ...
    def get_job_trigger(self, job_trigger_id, project_id: Any | None = ..., retry: Any | None = ..., timeout: Any | None = ..., metadata: Any | None = ...): ...
    def get_stored_info_type(self, stored_info_type_id, organization_id: Any | None = ..., project_id: Any | None = ..., retry: Any | None = ..., timeout: Any | None = ..., metadata: Any | None = ...): ...
    def inspect_content(self, project_id: Any | None = ..., inspect_config: Any | None = ..., item: Any | None = ..., inspect_template_name: Any | None = ..., retry: Any | None = ..., timeout: Any | None = ..., metadata: Any | None = ...): ...
    def list_deidentify_templates(self, organization_id: Any | None = ..., project_id: Any | None = ..., page_size: Any | None = ..., order_by: Any | None = ..., retry: Any | None = ..., timeout: Any | None = ..., metadata: Any | None = ...): ...
    def list_dlp_jobs(self, project_id: Any | None = ..., results_filter: Any | None = ..., page_size: Any | None = ..., job_type: Any | None = ..., order_by: Any | None = ..., retry: Any | None = ..., timeout: Any | None = ..., metadata: Any | None = ...): ...
    def list_info_types(self, language_code: Any | None = ..., results_filter: Any | None = ..., retry: Any | None = ..., timeout: Any | None = ..., metadata: Any | None = ...): ...
    def list_inspect_templates(self, organization_id: Any | None = ..., project_id: Any | None = ..., page_size: Any | None = ..., order_by: Any | None = ..., retry: Any | None = ..., timeout: Any | None = ..., metadata: Any | None = ...): ...
    def list_job_triggers(self, project_id: Any | None = ..., page_size: Any | None = ..., order_by: Any | None = ..., results_filter: Any | None = ..., retry: Any | None = ..., timeout: Any | None = ..., metadata: Any | None = ...): ...
    def list_stored_info_types(self, organization_id: Any | None = ..., project_id: Any | None = ..., page_size: Any | None = ..., order_by: Any | None = ..., retry: Any | None = ..., timeout: Any | None = ..., metadata: Any | None = ...): ...
    def redact_image(self, project_id: Any | None = ..., inspect_config: Any | None = ..., image_redaction_configs: Any | None = ..., include_findings: Any | None = ..., byte_item: Any | None = ..., retry: Any | None = ..., timeout: Any | None = ..., metadata: Any | None = ...): ...
    def reidentify_content(self, project_id: Any | None = ..., reidentify_config: Any | None = ..., inspect_config: Any | None = ..., item: Any | None = ..., inspect_template_name: Any | None = ..., reidentify_template_name: Any | None = ..., retry: Any | None = ..., timeout: Any | None = ..., metadata: Any | None = ...): ...
    def update_deidentify_template(self, template_id, organization_id: Any | None = ..., project_id: Any | None = ..., deidentify_template: Any | None = ..., update_mask: Any | None = ..., retry: Any | None = ..., timeout: Any | None = ..., metadata: Any | None = ...): ...
    def update_inspect_template(self, template_id, organization_id: Any | None = ..., project_id: Any | None = ..., inspect_template: Any | None = ..., update_mask: Any | None = ..., retry: Any | None = ..., timeout: Any | None = ..., metadata: Any | None = ...): ...
    def update_job_trigger(self, job_trigger_id, project_id: Any | None = ..., job_trigger: Any | None = ..., update_mask: Any | None = ..., retry: Any | None = ..., timeout: Any | None = ..., metadata: Any | None = ...): ...
    def update_stored_info_type(self, stored_info_type_id, organization_id: Any | None = ..., project_id: Any | None = ..., config: Any | None = ..., update_mask: Any | None = ..., retry: Any | None = ..., timeout: Any | None = ..., metadata: Any | None = ...): ...
