from airflow.contrib.hooks.gcp_api_base_hook import GoogleCloudBaseHook as GoogleCloudBaseHook
from typing import Any

class GoogleCloudKMSHook(GoogleCloudBaseHook):
    def __init__(self, gcp_conn_id: str = ..., delegate_to: Any | None = ...) -> None: ...
    def get_conn(self): ...
    def encrypt(self, key_name, plaintext, authenticated_data: Any | None = ...): ...
    def decrypt(self, key_name, ciphertext, authenticated_data: Any | None = ...): ...
