from airflow import AirflowException as AirflowException, version as version
from airflow.contrib.hooks.gcp_api_base_hook import GoogleCloudBaseHook as GoogleCloudBaseHook
from typing import Any

OPERATIONAL_POLL_INTERVAL: int

class GKEClusterHook(GoogleCloudBaseHook):
    location: Any
    def __init__(self, gcp_conn_id: str = ..., delegate_to: Any | None = ..., location: Any | None = ...) -> None: ...
    def get_client(self): ...
    def wait_for_operation(self, operation, project_id: Any | None = ...): ...
    def get_operation(self, operation_name, project_id: Any | None = ...): ...
    def delete_cluster(self, name, project_id: Any | None = ..., retry=..., timeout=...): ...
    def create_cluster(self, cluster, project_id: Any | None = ..., retry=..., timeout=...): ...
    def get_cluster(self, name, project_id: Any | None = ..., retry=..., timeout=...): ...
