from airflow.contrib.hooks.gcp_api_base_hook import GoogleCloudBaseHook as GoogleCloudBaseHook
from typing import Any

class CloudNaturalLanguageHook(GoogleCloudBaseHook):
    def __init__(self, gcp_conn_id: str = ..., delegate_to: Any | None = ...) -> None: ...
    def get_conn(self): ...
    def analyze_entities(self, document, encoding_type: Any | None = ..., retry: Any | None = ..., timeout: Any | None = ..., metadata: Any | None = ...): ...
    def analyze_entity_sentiment(self, document, encoding_type: Any | None = ..., retry: Any | None = ..., timeout: Any | None = ..., metadata: Any | None = ...): ...
    def analyze_sentiment(self, document, encoding_type: Any | None = ..., retry: Any | None = ..., timeout: Any | None = ..., metadata: Any | None = ...): ...
    def analyze_syntax(self, document, encoding_type: Any | None = ..., retry: Any | None = ..., timeout: Any | None = ..., metadata: Any | None = ...): ...
    def annotate_text(self, document, features, encoding_type: Any | None = ..., retry: Any | None = ..., timeout: Any | None = ..., metadata: Any | None = ...): ...
    def classify_text(self, document, retry: Any | None = ..., timeout: Any | None = ..., metadata: Any | None = ...): ...
