from airflow.hooks.dbapi_hook import DbApiHook as DbApiHook
from typing import Any

class PinotDbApiHook(DbApiHook):
    conn_name_attr: str
    default_conn_name: str
    supports_autocommit: bool
    def __init__(self, *args, **kwargs) -> None: ...
    def get_conn(self): ...
    def get_uri(self): ...
    def get_records(self, sql): ...
    def get_first(self, sql): ...
    def set_autocommit(self, conn, autocommit) -> None: ...
    def insert_rows(self, table, rows, target_fields: Any | None = ..., commit_every: int = ...) -> None: ...
