from airflow.exceptions import AirflowException as AirflowException
from airflow.hooks.base_hook import BaseHook as BaseHook
from typing import Any

class SparkSqlHook(BaseHook):
    def __init__(self, sql, conf: Any | None = ..., conn_id: str = ..., total_executor_cores: Any | None = ..., executor_cores: Any | None = ..., executor_memory: Any | None = ..., keytab: Any | None = ..., principal: Any | None = ..., master: str = ..., name: str = ..., num_executors: Any | None = ..., verbose: bool = ..., yarn_queue: str = ...) -> None: ...
    def get_conn(self) -> None: ...
    def run_query(self, cmd: str = ..., **kwargs) -> None: ...
    def kill(self) -> None: ...
