from airflow.task.task_runner.base_task_runner import BaseTaskRunner as BaseTaskRunner
from airflow.utils.helpers import reap_process_group as reap_process_group
from airflow.utils.operator_resources import Resources as Resources
from typing import Any

class CgroupTaskRunner(BaseTaskRunner):
    process: Any
    def __init__(self, local_task_job) -> None: ...
    mem_cgroup_name: Any
    cpu_cgroup_name: Any
    def start(self) -> None: ...
    def return_code(self): ...
    def terminate(self) -> None: ...
    def on_finish(self) -> None: ...
