from airflow import secrets as secrets
from airflow.exceptions import AirflowException as AirflowException
from airflow.models import Connection as Connection
from airflow.utils.db import provide_session as provide_session
from airflow.utils.log.logging_mixin import LoggingMixin as LoggingMixin
from typing import Any, List

CONN_ENV_PREFIX: str
log: Any

class BaseHook(LoggingMixin):
    def __init__(self, source) -> None: ...
    @classmethod
    def get_connections(cls, conn_id: str) -> List[Connection]: ...
    @classmethod
    def get_connection(cls, conn_id: str) -> Connection: ...
    @classmethod
    def get_hook(cls, conn_id: str) -> BaseHook: ...
    def get_conn(self) -> None: ...
    def get_records(self, sql) -> None: ...
    def get_pandas_df(self, sql) -> None: ...
    def run(self, sql) -> None: ...
