from airflow.exceptions import AirflowException as AirflowException
from airflow.hooks.base_hook import BaseHook as BaseHook
from typing import Any

class HttpHook(BaseHook):
    http_conn_id: Any
    method: Any
    base_url: Any
    def __init__(self, method: str = ..., http_conn_id: str = ...) -> None: ...
    def get_conn(self, headers: Any | None = ...): ...
    def run(self, endpoint, data: Any | None = ..., headers: Any | None = ..., extra_options: Any | None = ..., **request_kwargs): ...
    def check_response(self, response) -> None: ...
    def run_and_check(self, session, prepped_request, extra_options): ...
    def run_with_advanced_retry(self, _retry_args, *args, **kwargs): ...
