from airflow.hooks.base_hook import BaseHook as BaseHook
from typing import Any

class ZendeskHook(BaseHook):
    def __init__(self, zendesk_conn_id) -> None: ...
    def get_conn(self): ...
    def call(self, path, query: Any | None = ..., get_all_pages: bool = ..., side_loading: bool = ...): ...
