from airflow.contrib.hooks.aws_hook import AwsHook as AwsHook
from typing import Any

class AwsSnsHook(AwsHook):
    conn: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def get_conn(self): ...
    def publish_to_target(self, target_arn, message, subject: Any | None = ..., message_attributes: Any | None = ...): ...
