from airflow.contrib.hooks.aws_hook import AwsHook as AwsHook
from typing import Any

class AwsGlueCatalogHook(AwsHook):
    region_name: Any
    conn: Any
    def __init__(self, aws_conn_id: str = ..., region_name: Any | None = ..., *args, **kwargs) -> None: ...
    def get_conn(self): ...
    def get_partitions(self, database_name, table_name, expression: str = ..., page_size: Any | None = ..., max_items: Any | None = ...): ...
    def check_for_partition(self, database_name, table_name, expression): ...
    def get_table(self, database_name, table_name): ...
    def get_table_location(self, database_name, table_name): ...
