from airflow.contrib.hooks.gcp_api_base_hook import GoogleCloudBaseHook as GoogleCloudBaseHook
from typing import Any

class DatastoreHook(GoogleCloudBaseHook):
    connection: Any
    api_version: Any
    def __init__(self, datastore_conn_id: str = ..., delegate_to: Any | None = ..., api_version: str = ...) -> None: ...
    def get_conn(self, version: Any | None = ...): ...
    def allocate_ids(self, partial_keys): ...
    def begin_transaction(self): ...
    def commit(self, body): ...
    def lookup(self, keys, read_consistency: Any | None = ..., transaction: Any | None = ...): ...
    def rollback(self, transaction) -> None: ...
    def run_query(self, body): ...
    def get_operation(self, name): ...
    def delete_operation(self, name): ...
    def poll_operation_until_done(self, name, polling_interval_in_seconds): ...
    def export_to_storage_bucket(self, bucket, namespace: Any | None = ..., entity_filter: Any | None = ..., labels: Any | None = ...): ...
    def import_from_storage_bucket(self, bucket, file, namespace: Any | None = ..., entity_filter: Any | None = ..., labels: Any | None = ...): ...
