from airflow import AirflowException as AirflowException
from airflow.contrib.hooks.gcp_api_base_hook import GoogleCloudBaseHook as GoogleCloudBaseHook
from google.longrunning.operations_grpc_pb2 import Operation as Operation
from typing import Any

class CloudSpannerHook(GoogleCloudBaseHook):
    def __init__(self, gcp_conn_id: str = ..., delegate_to: Any | None = ...) -> None: ...
    def get_instance(self, instance_id, project_id: Any | None = ...): ...
    def create_instance(self, instance_id, configuration_name, node_count, display_name, project_id: Any | None = ...): ...
    def update_instance(self, instance_id, configuration_name, node_count, display_name, project_id: Any | None = ...): ...
    def delete_instance(self, instance_id, project_id: Any | None = ...) -> None: ...
    def get_database(self, instance_id, database_id, project_id: Any | None = ...): ...
    def create_database(self, instance_id, database_id, ddl_statements, project_id: Any | None = ...) -> None: ...
    def update_database(self, instance_id, database_id, ddl_statements, project_id: Any | None = ..., operation_id: Any | None = ...) -> None: ...
    def delete_database(self, instance_id, database_id, project_id: Any | None = ...) -> None: ...
    def execute_dml(self, instance_id, database_id, queries, project_id: Any | None = ...): ...
