from airflow.contrib.hooks.gcp_api_base_hook import GoogleCloudBaseHook as GoogleCloudBaseHook
from typing import Any

log: Any

class MLEngineHook(GoogleCloudBaseHook):
    def __init__(self, gcp_conn_id: str = ..., delegate_to: Any | None = ...) -> None: ...
    def get_conn(self): ...
    def create_job(self, project_id, job, use_existing_job_fn: Any | None = ...): ...
    def create_version(self, project_id, model_name, version_spec): ...
    def set_default_version(self, project_id, model_name, version_name): ...
    def list_versions(self, project_id, model_name): ...
    def delete_version(self, project_id, model_name, version_name): ...
    def create_model(self, project_id, model): ...
    def get_model(self, project_id, model_name): ...
