from airflow.utils import timezone as timezone
from dateutil.relativedelta import relativedelta as relativedelta
from typing import Any

cron_presets: Any

def date_range(start_date, end_date: Any | None = ..., num: Any | None = ..., delta: Any | None = ...): ...
def round_time(dt, delta, start_date=...): ...
def infer_time_unit(time_seconds_arr): ...
def scale_time_units(time_seconds_arr, unit): ...
def days_ago(n, hour: int = ..., minute: int = ..., second: int = ..., microsecond: int = ...): ...
def parse_execution_date(execution_date_str): ...
