from airflow.configuration import conf as conf
from typing import Any

log: Any

def TemporaryDirectory(suffix: str = ..., prefix: Any | None = ..., dir: Any | None = ...) -> None: ...
def mkdirs(path, mode) -> None: ...

ZIP_REGEX: Any

def correct_maybe_zipped(fileloc): ...
def open_maybe_zipped(fileloc, mode: str = ...): ...
def list_py_file_paths(directory, safe_mode=..., include_examples: Any | None = ...): ...
def find_dag_file_paths(file_paths, files, patterns, root, safe_mode) -> None: ...

COMMENT_PATTERN: Any

def might_contain_dag(file_path, safe_mode): ...
