from airflow.exceptions import AirflowException as AirflowException
from airflow.sensors.base_sensor_operator import BaseSensorOperator as BaseSensorOperator
from airflow.utils.decorators import apply_defaults as apply_defaults
from typing import Any

class SageMakerBaseSensor(BaseSensorOperator):
    ui_color: str
    aws_conn_id: Any
    def __init__(self, aws_conn_id: str = ..., *args, **kwargs) -> None: ...
    def poke(self, context): ...
    def non_terminal_states(self) -> None: ...
    def failed_states(self) -> None: ...
    def get_sagemaker_response(self) -> None: ...
    def get_failed_reason_from_response(self, response): ...
    def state_from_response(self, response) -> None: ...
