from airflow.hooks.dbapi_hook import DbApiHook as DbApiHook
from typing import Any

class PrestoException(Exception): ...

class PrestoHook(DbApiHook):
    conn_name_attr: str
    default_conn_name: str
    def get_conn(self): ...
    def get_isolation_level(self): ...
    def get_records(self, hql, parameters: Any | None = ...): ...
    def get_first(self, hql, parameters: Any | None = ...): ...
    def get_pandas_df(self, hql, parameters: Any | None = ...): ...
    def run(self, hql, parameters: Any | None = ...): ...
    def insert_rows(self, table, rows, target_fields: Any | None = ..., commit_every: int = ...) -> None: ...
